@apiHost = http://localhost:5001

GET {{apiHost}}/hello HTTP/1.1
Content-Type: application/json; charset=UTF-8

###
GET {{apiHost}}/download-audio?url=https://disk.sample.cat/samples/wav/suzume_no_tojimari.wav HTTP/1.1
Content-Type: application/json; charset=UTF-8

###
GET {{apiHost}}/inference?url=https://disk.sample.cat/samples/wav/suzume_no_tojimari.wav HTTP/1.1
Content-Type: application/json; charset=UTF-8